### ISSUE TITLE
`finalize` of local pointer in `every` loop

### ISSUE THREAD

**Issue by Tkachov** [fsantanna/ceu#24] opened 2015-03-15 16:08 UTC
Example:

    every SDL_REDRAW do
        var _SDL_Surface* srf;
        finalize
            srf = _TTF_RenderText_Blended(fnt, str, clr);
        with
            _SDL_FreeSurface(srf); // isn't freed after iteration's end
        end
    end

**Comment by fsantanna** [comment] 2015-04-07 19:27
I modified `ceu-sdl/samples/sdl5.ceu` to include your code and it seems to be working correctly.
A `printf` before the `_SDL_FreeSurface()` executes on every frame and `valgrind` doesn't detect leaks.
Please, reopen this issue if the problem persists for you (I couldn't reproduce the bug in newer versions.)

**Comment by Tkachov** [comment] 2015-04-08 13:30
I've reproduced it.

Sample code: http://tkachov.ru/files/leaky_simple.zip
There are two similar files: leak.ceu and no_leak.ceu, and I've marked the problem place with comments.

Summary:
when the variable is inside `every` scope (like in example I've wrote up there), it *does* finalize well. But when you move this variable declaration *out* of `every` scope, it does not. It finalizes only when it's outer scope is left, in our case when the application terminates.

No leak:  

    par/or do
        every SDL_REDRAW do
            var _SDL_Surface&? sfc;
            finalize sfc = _TTF_RenderText_Blended(...);
            with _SDL_FreeSurface(&sfc); end
            //...

Leak:  

    var _SDL_Surface&? sfc;
    par/or do
        every SDL_REDRAW do
            finalize sfc = _TTF_RenderText_Blended(...);
            with _SDL_FreeSurface(&sfc); end
            //...

**Comment by fsantanna** [comment] 2015-04-08 14:30
The `finalize` for an attribution is bounded to the scope of the reference, not to the scope of the assignment (just like a local variable).

As references have to be assigned exactly once (not more, not less), there's still a bug in the sense that the compiler doesn't detect the reference assignment inside a loop.

**Comment by fsantanna** [comment] 2015-04-10 00:41
Fixed in `master`: leaking code doesn't compile.

**Closed by fsantanna** 2015-04-10 00:41 UTC
Labels: bug
